# pod-with-port.yaml
#
apiVersion: v1
kind: Pod
metadata:
  name: itpath360
  namespace: dev
  labels:
   app: itpath360
spec:
  containers:
    - name: itpath360-app
      image: httpd
      ports:
        - containerPort: 80
          name: http
          protocol: TCP
#
# Here we run a pod in a specific namespace exposing a port (80) using TCP protocol
# kubectl create -f 02-pod-with-port.yaml
# kubectl get pods -n dev
# kubectl describe pod itpath360 -n dev

# kubectl delete pod itpath360 -n dev
